- name: Deploy Docker image from AWS ECR
  hosts: web
  vars:
    # Variables are passed via --extra-vars in your Jenkins command
    registry_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
    full_image: "{{ registry_url }}/{{ repo_name }}:{{ image_tag }}"

  tasks:
    # - name: Ensure AWS CLI and Docker dependencies are present
    #  ansible.builtin.apt:
    #    name: 
    #      - awscli
    #      - python3-pip
    #      - python3-docker
    #    state: present
    #    update_cache: yes

    - name: Get ECR login password from local AWS CLI
      ansible.builtin.shell: "aws ecr get-login-password --region {{ aws_region }}"
      register: ecr_password
      become: false
      # delegate_to: localhost
      # connection: local      
      # remote_user: "{{ lookup('env', 'USER') }}"
      # run_once: true
      no_log: true

    - name: Log into ECR registry on remote host
      community.docker.docker_login:
        registry_url: "{{ registry_url }}"
        username: AWS
        password: "{{ ecr_password.stdout }}"
        reauthorize: true

    - name: Pull image from ECR
      community.docker.docker_image:
        name: "{{ full_image }}"
        source: pull

    - name: Ensure container is running
      community.docker.docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ full_image }}"
        state: started
        restart_policy: always
        recreate: true
        published_ports:
          - "8081:5000"
