- hosts: web
  become: true
  tasks:
    - name: Pull latest Docker image
      shell: docker pull my-python-app:latest

    - name: Restart container
      shell: |
        docker rm -f {{CONTAINER_NAME}} || true
        docker run -d --name {{CONTAINER_NAME}} -p 8081:5000 {{ECR_URL}}:{{IMAGE_TAG}}"
